import Head from "next/head";
import LandingPage from "../components/LandingPage";
import About from "../components/About";
import Footer from "../components/Footer";
import Projects from "../components/Projects";
import BentoAbout from "../components/BentoAbout";
import Blinker from "../components/Blinker";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Archan Bhatta - Full Stack Dev</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicons/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicons/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicons/favicon-16x16.png"
        />
      </Head>
      <main className="full-page" id="content">
        <LandingPage />
        <About />
        <BentoAbout />
        <Projects />
        <Blinker />
      </main>
      <div orientation="right" className="email-container">
        <div className="email-display">
          <a href="mailto:archanme1@gmail.com">archanme1@gmail.com</a>
        </div>
      </div>
      <Footer />
    </div>
  );
}
